### ISSUE TITLE
NGINX Forward Proxy

### ISSUE THREAD

**Issue by tvvocold** [boekkooi/openshift-diy-nginx-php#17]
hi there, why i got : send() failed (1: Operation not permitted) while resolving, resolver: 8.8.8.8:53

      server {
        listen <%= ENV['OPENSHIFT_NGINX_IP'] %>:<%= ENV['OPENSHIFT_NGINX_PORT'] %>;
        server_name gist.domain.com;
        access_log off;

        location / {
            resolver 8.8.8.8;
            proxy_pass https://gist.github.com$request_uri;

            proxy_connect_timeout 6s;
            proxy_set_header Accept-Encoding "";
            proxy_set_header User-Agent $http_user_agent;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Server $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }

**Comment by boekkooi** [comment]
Hi @tvvocold,

You may want to take a look at http://nginx.org/en/docs/http/ngx_http_proxy_module.html but for the rest I can't help you with this. 
Maybe you should post your question/problem on https://stackoverflow.com or http://forum.nginx.org/.

Good luck.
