### ISSUE TITLE
OpenShift disconnecting on build causes incomplete extraction

### ISSUE THREAD

**Issue by StartledPhoenix** [boekkooi/openshift-diy-nginx-php#19]
Currently, when OpenShift disconnects on a build, it sometimes causes the extraction to be incomplete. The script (when executed the next time) sees that the folder is already extracted, and just uses that incomplete extraction.

The extracted folder needs to be deleted and re-extracted.

Not tested on other packages, but this is happening in php.

**Comment by boekkooi** [comment]
Thanks for the report I will take a look at what a good fix for this problem would be. 
Thanks for reporting!

**Comment by boekkooi** [comment]
The latest commit should fix your problem if not please let me know.

**Comment by StartledPhoenix** [comment]
Latest commit currently fails with

remote: Stopping DIY cartridge
remote: Building git ref 'master', commit cac7017
remote: nginx not installed.
remote: /tmp/build /var/lib/openshift/55007c58e0b8cd16120000b4
remote: Downloading pcre-8.36.tar.bz2.
remote: --2015-03-11 13:35:47--  ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-8.36.tar.bz2
remote:            => `./pcre-8.36.tar.bz2'
remote: Resolving ftp.csx.cam.ac.uk... 131.111.8.115
remote: Connecting to ftp.csx.cam.ac.uk|131.111.8.115|:21... connected.
remote: Logging in as anonymous ... Logged in!
remote: ==> SYST ... done.    ==> PWD ... done.
remote: ==> TYPE I ... done.  ==> CWD (1) /pub/software/programming/pcre ... done.
remote: ==> SIZE pcre-8.36.tar.bz2 ... 1533818
remote: ==> PASV ... done.    ==> RETR pcre-8.36.tar.bz2 ... done.
remote: Length: 1533818 (1.5M) (unauthoritative)
remote: 
remote:      0K .......... .......... .......... .......... ..........  3%  287K 5s
remote:     50K .......... .......... .......... .......... ..........  6%  560K 4s
remote:    100K .......... .......... .......... .......... .......... 10%  571K 3s
remote:    150K .......... .......... .......... .......... .......... 13%  587K 3s
remote:    200K .......... .......... .......... .......... .......... 16% 12.6M 2s
remote:    250K .......... .......... .......... .......... .......... 20%  580K 2s
remote:    300K .......... .......... .......... .......... .......... 23% 27.9M 2s
remote:    350K .......... .......... .......... .......... .......... 26%  579K 2s
remote:    400K .......... .......... .......... .......... .......... 30% 18.2M 1s
remote:    450K .......... .......... .......... .......... .......... 33%  591K 1s
remote:    500K .......... .......... .......... .......... .......... 36% 15.9M 1s
remote:    550K .......... .......... .......... .......... .......... 40% 1.31M 1s
remote:    600K .......... .......... .......... .......... .......... 43% 1.05M 1s
remote:    650K .......... .......... .......... .......... .......... 46% 19.6M 1s
remote:    700K .......... .......... .......... .......... .......... 50% 1.25M 1s
remote:    750K .......... .......... .......... .......... .......... 53% 1.06M 1s
remote:    800K .......... .......... .......... .......... .......... 56% 22.3M 1s
remote:    850K .......... .......... .......... .......... .......... 60%  124M 1s
remote:    900K .......... .......... .......... .......... .......... 63% 1.21M 1s
remote:    950K .......... .......... .......... .......... .......... 66% 1.11M 0s
remote:   1000K .......... .......... .......... .......... .......... 70% 45.5M 0s
remote:   1050K .......... .......... .......... .......... .......... 73%  212M 0s
remote:   1100K .......... .......... .......... .......... .......... 76% 22.3M 0s
remote:   1150K .......... .......... .......... .......... .......... 80% 1.29M 0s
remote:   1200K .......... .......... .......... .......... .......... 83% 1.06M 0s
remote:   1250K .......... .......... .......... .......... .......... 86% 31.5M 0s
remote:   1300K .......... .......... .......... .......... .......... 90%  168M 0s
remote:   1350K .......... .......... .......... .......... .......... 93%  215M 0s
remote:   1400K .......... .......... .......... .......... .......... 96% 36.8M 0s
remote:   1450K .......... .......... .......... .......... .......   100%  133M=1.1s
remote: 
remote: 2015-03-11 13:35:49 (1.39 MB/s) - `./pcre-8.36.tar.bz2' saved [1533818]
remote: 
remote: Unpacking pcre-8.36.tar.bz2.
remote: /var/lib/openshift/55007c58e0b8cd16120000b4/app-root/runtime/repo//.openshift/action_hooks/build_util: line 19: -8: substring expression < 0
remote: Libtool not installed.
remote: /tmp/build /tmp/build /var/lib/openshift/55007c58e0b8cd16120000b4
remote: Downloading libtool-2.4.5.tar.gz.
remote: --2015-03-11 13:35:49--  http://gnu.xl-mirror.nl/libtool/libtool-2.4.5.tar.gz
remote: Resolving gnu.xl-mirror.nl... 91.217.235.93
remote: Connecting to gnu.xl-mirror.nl|91.217.235.93|:80... connected.
remote: HTTP request sent, awaiting response... 200 OK
remote: Length: 1802567 (1.7M) [application/x-gzip]
remote: Saving to: `./libtool-2.4.5.tar.gz'
remote: 
remote:      0K .......... .......... .......... .......... ..........  2%  267K 6s
remote:     50K .......... .......... .......... .......... ..........  5%  531K 5s
remote:    100K .......... .......... .......... .......... ..........  8%  266K 5s
remote:    150K .......... .......... .......... .......... .......... 11%  551K 4s
remote:    200K .......... .......... .......... .......... .......... 14%  534K 4s
remote:    250K .......... .......... .......... .......... .......... 17% 12.2M 3s
remote:    300K .......... .......... .......... .......... .......... 19%  547K 3s
remote:    350K .......... .......... .......... .......... .......... 22% 24.6M 3s
remote:    400K .......... .......... .......... .......... .......... 25%  547K 2s
remote:    450K .......... .......... .......... .......... .......... 28% 26.2M 2s
remote:    500K .......... .......... .......... .......... .......... 31% 64.9M 2s
remote:    550K .......... .......... .......... .......... .......... 34%  548K 2s
remote:    600K .......... .......... .......... .......... .......... 36% 41.6M 2s
remote:    650K .......... .......... .......... .......... .......... 39% 48.9M 1s
remote:    700K .......... .......... .......... .......... .......... 42%  564K 1s
remote:    750K .......... .......... .......... .......... .......... 45% 16.9M 1s
remote:    800K .......... .......... .......... .......... .......... 48% 28.8M 1s
remote:    850K .......... .......... .......... .......... .......... 51% 91.2M 1s
remote:    900K .......... .......... .......... .......... .......... 53%  567K 1s
remote:    950K .......... .......... .......... .......... .......... 56% 20.1M 1s
remote:   1000K .......... .......... .......... .......... .......... 59% 51.7M 1s
remote:   1050K .......... .......... .......... .......... .......... 62% 40.8M 1s
remote:   1100K .......... .......... .......... .......... .......... 65% 43.4M 1s
remote:   1150K .......... .......... .......... .......... .......... 68%  212M 1s
remote:   1200K .......... .......... .......... .......... .......... 71%  571K 0s
remote:   1250K .......... .......... .......... .......... .......... 73% 14.4M 0s
remote:   1300K .......... .......... .......... .......... .......... 76%  111M 0s
remote:   1350K .......... .......... .......... .......... .......... 79%  168M 0s
remote:   1400K .......... .......... .......... .......... .......... 82%  173M 0s
remote:   1450K .......... .......... .......... .......... .......... 85% 27.9M 0s
remote:   1500K .......... .......... .......... .......... .......... 88%  119M 0s
remote:   1550K .......... .......... .......... .......... .......... 90%  576K 0s
remote:   1600K .......... .......... .......... .......... .......... 93% 17.0M 0s
remote:   1650K .......... .......... .......... .......... .......... 96% 30.3M 0s
remote:   1700K .......... .......... .......... .......... .......... 99%  219M 0s
remote:   1750K ..........                                            100% 19683G=1.3s
remote: 
remote: 2015-03-11 13:35:51 (1.31 MB/s) - `./libtool-2.4.5.tar.gz' saved [1802567/1802567]
remote: 
remote: Unpacking libtool-2.4.5.tar.gz.
remote: /var/lib/openshift/55007c58e0b8cd16120000b4/app-root/runtime/repo//.openshift/action_hooks/build_util: line 14: -7: substring expression < 0
remote: /var/lib/openshift/55007c58e0b8cd16120000b4/app-root/runtime/repo//.openshift/action_hooks/build_php: line 169: /var/lib/openshift/55007c58e0b8cd16120000b4/diy//runtime//php5/bin/php: No such file or directory
remote: PHP pecl mongo not installed or old version.
remote: /tmp/build /tmp/build /tmp/build /var/lib/openshift/55007c58e0b8cd16120000b4
remote: Downloading mongo-1.5.1.tgz.
remote: --2015-03-11 13:35:51--  http://pecl.php.net/get/mongo-1.5.1.tgz
remote: Resolving pecl.php.net... 76.75.200.106
remote: Connecting to pecl.php.net|76.75.200.106|:80... connected.
remote: HTTP request sent, awaiting response... 200 OK
remote: Length: 188885 (184K) [application/octet-stream]
remote: Saving to: `mongo-1.5.1.tgz'
remote: 
remote:      0K .......... .......... .......... .......... .......... 27% 1.11M 0s
remote:     50K .......... .......... .......... .......... .......... 54% 3.59M 0s
remote:    100K .......... .......... .......... .......... .......... 81% 2.33M 0s
remote:    150K .......... .......... ...Unpacking mongo-1.5.1.tgz.
remote: ....... ....                 100% 2.66M=0.09s
remote: 
remote: 2015-03-11 13:35:51 (1.98 MB/s) - `mongo-1.5.1.tgz' saved [188885/188885]
remote: 
remote: /var/lib/openshift/55007c58e0b8cd16120000b4/app-root/runtime/repo//.openshift/action_hooks/build_util: line 16: -4: substring expression < 0
remote: NodeJs local will be used
remote: Creating NPM proxy.
remote: Preparing build for deployment
remote: Deployment id is f9d18a44
remote: Activating deployment
remote: Pre-processing nginx config.
remote: cp: cannot create regular file `/var/lib/openshift/55007c58e0b8cd16120000b4/diy//runtime//nginx//conf/nginx.conf': No such file or directory
remote: -------------------------
remote: Git Post-Receive Result: failure
remote: Activation status: failure
remote: Activation failed for the following gears:
remote: 55007c58e0b8cd16120000b4 (Error activating gear: CLIENT_ERROR: Failed to execute action hook 'deploy' for 55007c58e0b8cd16120000b4 application nginxtest
remote: #<IO:0x000000007083c0>
remote: #<IO:0x00000000708348>
remote: )
remote: Deployment completed with status: failure
remote: postreceive failed

**Comment by boekkooi** [comment]
Sorry about that it seems that openshift was using a different bash version. 
The problem should be fixed now.

**Comment by StartledPhoenix** [comment]
Works fine now, thanks!

**Comment by boekkooi** [comment]
No problem let me know if you have any more problems
