### ISSUE TITLE
The remote end hung up unexpectedly

### ISSUE THREAD

**Issue by tomc3** [boekkooi/openshift-diy-nginx-php#23]
Hello i'm getting this error every-time I tries to install.

```
remote: checking for PQprotocolVersion in -lpq... Connection to test-name.rhcloud.com closed by remote
 host.
fatal: The remote end hung up unexpectedly
error: error in sideband demultiplexer
To ssh://55b7be68e0b8cdb3bf0011f8@test-name.rhcloud.com/~/git/test.git/
   75bb35b..752b613  master -> master
error: failed to push some refs to 'ssh://55b7be68e0b8cdb3bf0011f8@test-name.rhcloud.com/~/git/test.git/'
```

**Comment by boekkooi** [comment]
To my knowledge this is a problem with git not this repo. 

Here are some threads and related issue that may help:
- [Git responds with 'error in sideband demultiplexer'](http://stackoverflow.com/questions/4582849/git-responds-with-error-in-sideband-demultiplexer)
- [Error in sideband demultiplexer with a git post-receive hook](http://stackoverflow.com/questions/9592908/error-in-sideband-demultiplexer-with-a-git-post-receive-hook)
- https://github.com/openruko/gitmouth/issues/7

Good luck and thanks for reporting! (If this is a actual issue with this repo then please reopen the issue)

**Comment by mrofi** [comment]
I had same issue and solved with this way :
```
rhc ssh <app_name>
cd $OPENSHIFT_REPO_DIR
.openshift/action_hooks/stop
.openshift/action_hooks/build
wait and wait...
.openshift/action_hooks/deploy
.openshift/action_hooks/start
```
