### ISSUE TITLE
php installation fails

### ISSUE THREAD

**Issue by josefstr** [boekkooi/openshift-diy-nginx-php#28]
Installation doesn't finish as php didn't get installed. Invoking the build script again brings the same error as on first try.

bash-4.1$ ./build
nginx up to date, version: 1.7.10.
PHP not installed.
Libtool up to date, version: 2.4.6.
LibMCrypt up to date, version: 2.5.8.
ICU up to date, version: 54.1.
Bison up to date, version: 2.7.12.
Re2c up to date, version: 0.14.3.
/tmp/build /var/lib/openshift/56xxxxxxx0f2/app-root/runtime/repo/.openshift/action_hooks
Downloading php-5.6.6.tar.gz:
- skipping file exists.
Unpacking php-5.6.6.tar.gz:
- skipping directory exists.
/tmp/build/php-5.6.6 /tmp/build /var/lib/openshift/56xxxxxxx0f2/app-root/runtime/repo/.openshift/action_hooks
Configuring PHP.
/var/lib/openshift/56xxxxxxx0f2/app-root/runtime/repo//.openshift/action_hooks/build_php: line 22: ./configure: No such file or directory

**Comment by boekkooi** [comment]
Try sshing into the cartridge and remove the build php build directory (`rm -rf ${OPENSHIFT_TMP_DIR}/build/php-5.6.6/` and `rm ${OPENSHIFT_TMP_DIR}/build/php-5.6.6.tar.gz`).

**Comment by josefstr** [comment]
Well I've deleted the application twice and tried it again, and at the end the compilation run without error. So this can be closed, but thanks for your help.

**Comment by boekkooi** [comment]
@josefstr No problem, guess third time was the charm :smile:
